import tkinter

master_window = tkinter.Tk()
master_window.geometry("400x400")

#Menu
menu1 = tkinter.Menu(master_window)
master_window.config(menu=menu1)
filemenu = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="File", menu=filemenu)
filemenu.add_command(label="New Text File")
filemenu.add_command(label="New File...")
filemenu.add_command(label="New Window")
filemenu.add_command(label="New Window with Profile")
filemenu.add_separator()
filemenu.add_command(label="Open File...")
filemenu.add_command(label="Open Folder...")
filemenu.add_command(label="Open Workspace from File...")
filemenu.add_command(label="Open Recent")
filemenu.add_separator()
filemenu.add_command(label="Add Folder to Workspace...")
filemenu.add_command(label="Save Workspace As...")
filemenu.add_command(label="Duplicate Workspace")
filemenu.add_separator()
filemenu.add_command(label="Save")
filemenu.add_command(label="Save As...")
filemenu.add_command(label="Save All")
filemenu.add_separator()
filemenu.add_command(label="Share")
filemenu.add_separator()
filemenu.add_command(label="Auto Save")
filemenu.add_command(label="Preferences")
filemenu.add_separator()
filemenu.add_command(label="Revert File")
filemenu.add_command(label="Close Editor")
filemenu.add_command(label="Close Folder")
filemenu.add_command(label="Close Window")
filemenu.add_separator()
filemenu.add_command(label="Exit", command=master_window.destroy)

editmenu = tkinter.Menu(menu1, tearoff=0)
menu1.add_cascade(label="Edit", menu=editmenu)
editmenu.add_command(label="Undo")
editmenu.add_command(label="Redo")
editmenu.add_separator()
editmenu.add_command(label="Cut")
editmenu.add_command(label="Copy")
editmenu.add_command(label="Paste")
editmenu.add_separator()
editmenu.add_command(label="Find")
editmenu.add_command(label="Replace")
editmenu.add_separator()
editmenu.add_command(label="Find in Files")
editmenu.add_command(label="Replace in Files")
editmenu.add_separator()
editmenu.add_command(label="Toggle Line Comment")
editmenu.add_command(label="Toggle Block Comment")
editmenu.add_command(label="Emmet: Expand Abbreviation")
editmenu.add_separator()
editmenu.add_command(label="Exit", command=master_window.destroy)

master_window.mainloop()